config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get "/about" => "public/homes#about", as: "about"

  devise_for :users,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

  namespace :public do
    get :searches, to: 'searches#searches'
    resources :books do
     resource :favorites, only: [:index, :create, :destroy]
     resources :comments, only: [:create, :destroy]
    end
    patch '/books/:id' => 'books#update'
    resources :users, except: [:show, :edit, :update]
    get '/users/my_page' => 'users#show'
    get '/users/information/edit' => 'users#edit'
    patch '/users/information' => 'users#update'
    get '/users/unsubscribe' => 'users#unsubscribe'
    patch '/users/withdraw' => 'users#withdraw'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :comments
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :email)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <h4 class="bg-light" style="width: 360px;"><%= @user.name %>さんの会員情報編集</h4>
      <%= form_with model: @user, url: admin_user_path(@user), local:true do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td class="form-group"><%= @user.id %></td>
          </tr>
          <tr>
            <th>名前</th>
            <td class="form-group" style="width:20%;"><%= f.text_field :name, class:"form-control name", placeholder:@user.name %></td>
          </tr>
          <tr>
            <th style="width:20%;">メールアドレス</th>
            <td class="form-group" colspan="2"><%= f.text_field :email, class:"form-control email", placeholder:@user.email %></td>
          </tr>
          <tr>
            <th >会員ステータス</th>
            <td class="form-group">
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "有効" %>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "退会" %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="form-group text-center">
        <%= f.submit "変更を保存", class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col m-3">
      <h4><%= @user.name %>さんの会員詳細</h4>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th>名前</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <% if @user.is_deleted? == true %>
    	        <td class="text-danger">退会</td>
				    <% else %>
				      <td class="text-success">有効</td>
				    <% end %>
          </tr>
          <tr>
            <th>投稿</th>
            <% @user.books.each do |book| %>
            <td><%= book.title %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="text-center mb-3">
      <div class="d-inline-block mr-5">
        <%= link_to '編集する', edit_admin_user_path, class:"btn btn-success" %>
      </div>
      <div class="d-inline-block ml-5">
        <%= link_to '会員一覧に戻る',admin_path, class:"btn btn-primary" %>
      </div>
      </div>
    </div>
  </div>
</div>