config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get "/about" => "public/homes#about", as: "about"

  devise_for :users,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

  namespace :public do
    get :searches, to: 'searches#searches'
    resources :books do
     resource :favorites, only: [:index, :create, :destroy]
     resources :comments, only: [:create, :destroy]
    end
    patch '/books/:id' => 'books#update'
    resources :users, except: [:show, :edit, :update]
    get '/users/my_page' => 'users#show'
    get '/users/information/edit' => 'users#edit'
    patch '/users/information' => 'users#update'
    get '/users/unsubscribe' => 'users#unsubscribe'
    patch '/users/withdraw' => 'users#withdraw'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :comments
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_tag_relations, dependent: :destroy
  has_many :tags, through: :book_tag_relations, dependent: :destroy

  validates :title, presence: true
  validates :body,presence: true, length: {maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_tag_relation.rb
class BookTagRelation < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :book_tag_relations, dependent: :destroy
  has_many :books, through: :book_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
    @comments = Comment.page(params[:pege])
  end

  def show
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @users = User.page(params[:pege])
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/fe616d070e.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to '会員一覧', admin_path, class: "btn btn-light" %>
            </li>
            <li class="nav-item">
              <%= link_to 'コメント一覧', admin_comments_path, class: "btn btn-light" %>
            </li>
            <li>
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-light" %>
            </li>


            <% elsif user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'HOME', root_path, class: "btn btn-light" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", public_users_my_page_path, class: "btn btn-light" %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_public_book_path, class: "btn btn-light" %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿一覧', public_books_path, class: "btn btn-light" %>
            </li>
            <li>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-light" %>
            </li>

            <% else %>
            <li class="nav-item">
              <%= link_to 'HOME', root_path, class: "btn btn-light" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: "btn btn-light" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", public_books_path, class: "btn btn-light" %>
            </li>
            <li>
              <%= link_to '新規登録', new_user_registration_path, class: "btn btn-light" %>
            </li>
            <li>
              <%= link_to 'ログイン', new_user_session_path, class: "btn btn-light" %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
        <div class="col-12 col-md-8 ml-auto my-3">
          <%= form_tag(public_searches_path, method: :get) do %>
            <div class="input-group mb-3">
              <%= text_field_tag :keyword, params[:keyword], class: 'form-control' %>
              <div class="input-group-append">
                <%= button_tag type: 'submit', name: nil, class: 'btn btn-outline-secondary' do %>
                  <i class="fa-solid fa-magnifying-glass"></i>
                <% end %>
              </div>
            </div>
            <div class="d-flex flex-row bd-highlight md-12">
              <% Tag.all.each do |t| %>
                <p class="flex-fill bd-highlight"><%= check_box :tag_ids, t.name %><%= t.name %></p>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <main class="mb-auto">
    <%= yield %>
    </main>
  </body>
</html>